version: '3'
services:
  zf:
    build: .
    container_name: zf
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
    restart: always
  zf_mysql:
    image: mysql:5.7
    container_name: zf_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zf_mysql
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: